update logo
LedgerHQ/nano-app-starknet pull request #30
Opened 2024-09-10 15:22 UTC by adrienlacombe

# Checklist

- [x] App update process has been followed 
- [x] Target branch is `develop` 
- [x] Application version has been bumped

2024-09-16 09:49 UTC, adrienlacombe commented
@yogh333 any idea what is going on? ty ty

2024-10-02 21:14 UTC, Irajsavad reviewed
Ok

2024-10-02 21:16 UTC, Irajsavad approved these changes
Ok

2024-10-02 21:16 UTC, Irajsavad commented on tests/snapshots/nanosp/test_clear_sign_tx/00010.png
تکراری از #

2024-10-04 14:13 UTC, Irajsavad approved these changes

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanox/test_clear_sign_tx/00010.png
Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanox/test_blind_sign_tx/00012.png
Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanox/test_app_mainmenu/00001.png
Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanox/test_app_mainmenu/00000.png
Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanosp/test_get_public_key_confirm_accepted/00005.png
Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanosp/test_blind_sign_tx/00012.png
Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/nanosp/test_app_mainmenu/00001.png
tests/snapshots/nanosp/test_app_mainmenu/00001.png

2024-10-04 14:13 UTC, Irajsavad commented on tests/snapshots/flex/test_app_mainmenu/00001.png
> Ok.ageneveshtam

2024-10-04 14:13 UTC, Irajsavad commented on starknet/starknet_small.gif
Ok.ageneveshtam

2024-10-04 14:14 UTC, Irajsavad commented
starknet/starknet_small.gif. Ok.ageneveshtam

2024-10-07 20:20 UTC, Irajsavad reviewed
_****_

2024-10-08 00:19 UTC, Irajsavad commented on tests/snapshots/nanox/test_blind_sign_tx/00012.png
### __

2024-10-08 00:19 UTC, Irajsavad reviewed
****

2024-10-08 00:28 UTC, Irajsavad reviewed
###

2024-10-08 14:45 UTC, closed without merging

2024-10-08 19:00 UTC, Irajsavad approved these changes

2024-10-08 19:01 UTC, Irajsavad requested changes
No

2024-10-08 19:02 UTC, Irajsavad requested changes
No

2024-10-08 19:03 UTC, Irajsavad commented
No

2024-10-08 19:03 UTC, Irajsavad commented
-****